// src/models2.js
export const data = [
  {
    id: "1",
    name: "展品1",
    url: "./assets/models2/1.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "2",
    name: "展品1",
    url: "./assets/models2/2.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "3",
    name: "展品1",
    url: "./assets/models2/3.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "4",
    name: "展品1",
    url: "./assets/models2/4.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "5",
    name: "展品1",
    url: "./assets/models2/5.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "6",
    name: "展品1",
    url: "./assets/models2/6.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "7",
    name: "展品1",
    url: "./assets/models2/7.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "8",
    name: "展品1",
    url: "./assets/models2/8.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "9",
    name: "展品1",
    url: "./assets/models2/9.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "10",
    name: "展品1",
    url: "./assets/models2/10.glb",
    position: { x: 0, y: -2, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "11",
    name: "展品1",
    url: "./assets/models2/11.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "12",
    name: "展品1",
    url: "./assets/models2/12.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "13",
    name: "展品1",
    url: "./assets/models2/13.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "14",
    name: "展品1",
    url: "./assets/models2/14.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },  {
    id: "15",
    name: "展品1",
    url: "./assets/models2/15.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },  {
    id: "16",
    name: "展品1",
    url: "./assets/models2/16.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },  {
    id: "17",
    name: "展品1",
    url: "./assets/models2/17.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },  {
    id: "18",
    name: "展品1",
    url: "./assets/models2/18.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },  {
    id: "19",
    name: "展品1",
    url: "./assets/models2/19.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "20",
    name: "展品1",
    url: "./assets/models2/20.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "21",
    name: "展品1",
    url: "./assets/models2/21.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },  {
    id: "22",
    name: "展品1",
    url: "./assets/models2/22.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },  {
    id: "23",
    name: "展品1",
    url: "./assets/models2/23.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },  {
    id: "24",
    name: "展品1",
    url: "./assets/models2/24.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },  {
    id: "25",
    name: "展品1",
    url: "./assets/models2/25.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },  {
    id: "26",
    name: "展品1",
    url: "./assets/models2/26.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },  
  {
    id: "27",
    name: "展品1",
    url: "./assets/models2/27.glb",
    position: { x: 0, y: 0, z: 0 },
    scale: { x: 5, y: 5, z: 5 },
    rotation: { x: 0, y: 0, z: 0 },
    desc: "一个绚丽多彩的彩虹。",
    type: "model",
  },
  {
    id: "guide1",
    name: "导览点1",
    position: { x: 10, y: 1, z: 5 },
    view: { x: 11, y: 1, z: 6 },
    desc: "这是一个导览点。",
    type: "guide",
  },
  // 添加其他展品和导览点的数据
];
